SRC_TRG_TXT_DIC = {
    # Human face
    'tanned': (['face'],
               ['tanned face']),
    'pale': (['face'],
             ['pale face']),
    'makeup': (['person'],
               ['person with makeup']),
    'no_makeup': (['person'],
                  ['person without makeup']),
    'old': (['person'],
            ['old person']),
    'young': (['person'],
              ['young person']),
    'beards': (['person'],
               ['person with beards']),
    'angry': (['face'],
              ['angry face']),
    'surprised': (['face'],
                  ['surprised face']),
    'smiling': (['face'],
                ['smiling face']),
    'blond_hair': (['person'],
                   ['person with blond hair']),
    'red_hair': (['person'],
                 ['person with red hair']),
    'grey_hair': (['person'],
                  ['person with red hair']),
    'curly_hair': (['person'],
                   ['person with curly hair']),
    'giggling': (['person'],
                 ['giggling person']),
    'CuAP_giggling': (['person'],
                 ['person, in A person giggling may have a smile on their face and make a sound that indicates they are amused']),
    'CuPL_giggling': (['person'],
                      ['If you hear someone giggling, it may be difficult to identify the person']),
    'ACT_giggling': (['person'],
                     ['A child laughs very loudly']),
    'sobbing': (['person'],
                 ['sobbing person']),
    'CuAP_sobbing': (['person'],
                 ['A person who is sobbing may have tears streaming down their face and they may be making an audible cry']),
    'CuPL_sobbing': (['person'],
                     ['A sobbing person generally looks miserable']),
    'ACT_sobbing': (['person'],
                    ['A baby cries and a woman and man speak']),

    'nicolas': (['Person'],
                ['Nicolas Cage']),
    'zuckerberg': (['Person'],
                   ['Mark Zuckerberg']),
    'benedict': (['Person'],
              ['Benedict Cumberbatch']),
    'gogh': (['photo'],
             ['painting by Gogh']),
    'frida': (['photo'],
              ['self-portrait by Frida Kahlo']),
    'modigliani': (['photo'],
                   ['Painting in Modigliani style']),
    'sketch': (['photo'],
              ['sketch']),
    'watercolor': (['photo'],
                   ['Watercolor Art with Thick Brushstrokes']),
    'elf': (['Human'],
            ['Tolkien elf']),
    'super_saiyan': (['Human'],
                     ['Super saiyan']),
    'pixar': (['Human'],
              ['3D render in the style of Pixar']),
    'neanderthal': (['Human'],
                    ['Neanderthal']),
    'zombie': (['Human'],
               ['Zombie']),
    'jocker': (['Human'],
               ['The Jocker']),


    # Dog face
    'dog_nicolas': (['Dog'],
                    ['Nicolas Cage']),
    'dog_yorkshire': (['Dog'],
                      ['Yorkshire Terrier']),
    'dog_smiling': (['Dog'],
                    ['Smiling Dog']),
    'dog_zombie': (['Dog'],
                   ['Zombie']),
    'dog_super_saiyan': (['Dog'],
                         ['Super saiyan']),
    'dog_venom': (['Dog'],
                  ['Venom']),
    'dog_bear': (['Dog'],
                 ['Bear']),
    'dog_fox': (['Dog'],
                ['Fox']),
    'dog_wolf': (['Dog'],
                 ['Wolf']),
    'dog_hamster': (['Dog'],
                    ['Hamster']),


    # Church
    'church_snow': (['Church'],
                    ['Snow Coverd Church']),
    'church_night': (['Church'],
                     ['Church at night']),
    'church_red_brick': (['Church'],
                         ['Red brick wall Church']),
    'church_golden': (['Church'],
                      ['Golden Church']),
    'church_wooden_house': (['Church'],
                            ['Wooden House']),
    'church_gothic': (['Church'],
                      ['Gothic Church']),
    'church_ancient_tower': (['Church'],
                             ['Ancient traditional Asian tower']),
    'church_temple': (['Church'],
                      ['Temple']),
    'church_factory': (['church'],
                       ['factory with chimneys']),
    'church_department_store': (['church'],
                                ['department store']),
    # Adding Sound-Related Text
    'church_exploded': (['Church'],
                        ['Exploded Church']),
    'church_fire': (['Church'],
                    ['Church on fire']),
    'ACT_fire': (['Church'],
                 ['Church in a loud cracking sound']),
    'CuPL_fire': (['Church'],
                  ['A church with fire is a place of worship and sacrifice']),
    'CuAP_fire': (['Church'],
                  ['Church, in A fire can be identified by its flames which is typically red, orange, or yellow.']),

    'church_rain': (['Church'],
                    ['Church in the rain']),
    'church_thunder': (['Church'],
                       ['Church with thunderstorm']),
    'CuAP_thunder': (['Church'],
                       ['Church in a thunder is produced by a lightning which is a sudden electrostatic discharge that occurs during a thunderstorm']),
    'ACT_thunder': (['Church'],
                    ['Church, in heavy wind and rain falling']),
    'CuPL_thunder': (['Church'],
                     ['A Church in thunderstorm looks like a dark and scary place']),


    # Bedroom
    'bedroom_blue': (['Bedroom'],
                     ['Blue tone Bedroom']),
    'bedroom_green': (['Bedroom'],
                      ['Green tone Bedroom']),
    'bedroom_golden': (['Bedroom'],
                       ['Golden Bedroom']),
    'bedroom_princess': (['Bedroom'],
                         ['Princess Bedroom']),
    'bedroom_palace': (['Bedroom'],
                       ['Palace Bedroom']),
    'bedroom_wooden': (['Bedroom'],
                       ['Wooden Bedroom']),
    'bedroom_fire': (['Bedroom'],
                    ['Bedroom on fire']),


}